name: Golang CI

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
            - name: "Download Dependencies"
              run: go install
            - name: "Run Unit Tests"
              run: go test

    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
            - name: "Download Dependencies"
              run: go install
            - name: "Download golangci-lint"
              run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.63.4 && source ~/.bashrc
            - name: "Lint Package"
              run: golangci-lint